language messages en_US
set encoding=utf-8

" Get rid of legacy stuff
set nocompatible
set backspace=indent,eol,start

" Turn on syntax highligh and line numbers by default
syntax on
set nu

" Use system clipboard 
set clipboard=unnamed

" Enable mouse support
if has('mouse')
  set mouse=a
endif

" Turn off annoying beep sound
set visualbell

" NOTE: Shall think about better backup strategy
set nobackup
set noswapfile

set history=50
set ruler
set showcmd

" Search settings
set incsearch
set ignorecase
set smartcase
set hlsearch

" Indentation settings
filetype plugin indent on
autocmd FileType text setlocal textwidth=79
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
" ruby specific
:autocmd Filetype ruby set softtabstop=2
:autocmd Filetype ruby set shiftwidth=2
:autocmd Filetype ruby set tabstop=2

let python_highlight_all=1

nnoremap / /\v
vnoremap / /\v

" Pretty whitespaces highlight 
set listchars=tab:▸\ ,eol:¬ 
autocmd filetype html,xml set listchars-=tab:▸\ ,eol:¬ 
highlight SpecialKey guifg=#505070


" Turn off arrow keys in normal and insert modes
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>

nnoremap j gj
nnoremap k gk

" More convenient way to return to normal mode from insert mode
inoremap jj <ESC>

" Remap <leader> to , key
let mapleader = ","

" Toggle whitespace highlighting
nmap <leader>l :set list!<CR> 

" Delete to the end of line
nmap <leader>d d$

" Call CommandT
nnoremap <leader>t :CommandT<CR>
" fixing ESC in OS X terminal
let g:CommandTCancelMap=['<ESC>','<C-c>']

" Use <tab> to jump to matching bracket
nnoremap <tab> %
vnoremap <tab> %

" For more rapid command insertion
nnoremap ; :

" Edit and reload vimrc (this file)
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Change working directory automatically
"set autochdir
 
" Command-T configuration
let g:CommandTMaxHeight=15

if has("gui_running")
    " Hide the mouse when typing text
    set mousehide 

    " Get rid of toolbar
    set guioptions-=T 

    " Set fancy font
    if has("gui_mac") || has("gui_macvim")
        set gfn=Menlo\ Regular:h12
    endif

    if has("gui_win32") || has("gui_win32s")
        set gfn=Consolas:h10.5:cDEFAULT
    endif

    colorscheme molokai
endif
