# use .bashrc_local for settings specific to one system
[[ -f ~/.bashrc_local ]] && . ~/.bashrc_local

export CLICOLOR=1

alias reload!='. ~/.bashrc'
alias ebash='vim ~/.bashrc'

if [ ! `uname` == "Darwin" ]; then
    alias ls='ls --color=auto'
fi
alias la='ls -A'
alias ..='cd ..'

# Git

alias glog='git log'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gca!='git commit -a -m "^_^"'
alias gcam='git commit --amend'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb' 

# git-svn
alias gsr='git svn rebase'
alias gsd='git svn dcommit'

alias gignore!='git status -s | sed -n -e "s/?? //p" >> .gitignore'

alias gbname='git name-rev --name-only HEAD'

# update current branch from remote branch with the same name in origin repo
alias gpull='gbname | xargs git pull origin'
# and push it
alias gpush='gbname | xargs git push origin'

