# use .bashrc_local for settings specific to one system
[[ -f ~/.bashrc_local ]] && . ~/.bashrc_local

export EDITOR=vim
export HOMEBREW_EDITOR=vim

alias reload!='. ~/.bashrc'
alias ebash='vim ~/.bashrc'

if [ `uname` == "Darwin" ]; then
    export CLICOLOR=1
else
    alias ls='ls --color=auto'
fi

alias la='ls -A'
alias ..='cd ..'

# Git

alias glog='git log'
alias glogst='git log --stat'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gca!='git commit -a -m "^_^"'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb' 
alias gmrsq='git merge --squash'

# append all unversioned files to .gitignore
alias gignore!='git status -s | sed -n -e "s#?? #/#p" >> .gitignore'

alias gbname='git name-rev --name-only HEAD'

# update current branch from remote branch with the same name in origin repo
alias gpull="gbname | xargs -i git pull origin '{}':'{}'"
# and push it
alias gpush="gbname | xargs -i git push origin '{}':'{}'"

